2018-08-16 16:51:08,103 ERROR: Exception on /ajax [GET] [in /home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/microblog/app/routes.py", line 58, in ajax
    return render_template('ajax.html', title='Start Recording', posts=posts.items, next_url=next_url, prev_url=prev_url)
NameError: name 'posts' is not defined
2018-08-16 16:51:38,332 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 14:04:18,482 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 14:08:53,248 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 15:25:11,135 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 16:24:44,329 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 16:27:27,091 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 16:29:45,607 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 16:31:26,732 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 16:33:38,169 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:49]
2018-08-17 22:58:58,522 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:23:25,308 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:23:56,340 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:23:58,497 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:24:24,094 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:24:41,755 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:47:06,533 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-17 23:54:38,235 INFO: Microblog startup [in /Users/jianrongtang/microblog/app/__init__.py:49]
2018-08-18 14:12:57,709 INFO: Microblog startup [in /Users/jianrongtang/Webserver-v1/app/__init__.py:49]
2018-08-18 14:12:59,664 INFO: Microblog startup [in /Users/jianrongtang/Webserver-v1/app/__init__.py:49]
2018-08-18 14:13:03,864 ERROR: Exception on /ajax [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jianrongtang/Webserver-v1/app/routes.py", line 58, in ajax
    return render_template('ajax.html', title='Start Recording')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/jianrongtang/Webserver-v1/app/templates/ajax.html", line 32, in template
    {% block app_content %}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
